### ISSUE TITLE
possibility of use spritebatch for drawimg?

### ISSUE THREAD

**Issue by SiENcE** [trubblegum/Gspot#2]
Gspot is very handy.

I use gspot for a game and it's a little bit difficult for me to improve it to use spritebatch.

Can you help?

**Comment by trubblegum** [comment]
probably the best way to do it would be to extend an element (probably image) with offset variables and a draw function which draws a sprite instead of an image.

**Comment by SiENcE** [comment]
this seems possible, but i'm only using gspot and i'm not very firm with the concept. so i don't want to break anything.

**Comment by trubblegum** [comment]
Are you saying you're not using any native love2d functions?
What concept is it that you're not familiar with?
Break? How?
What is this I don't even.

**Comment by SiENcE** [comment]
Immediate guis.
It was only a suggestion to make gspot better. I really appreciate this gui! I currently don't have the time to dig into gspot yet. Maybe later. Thanks for the hints. cheers!

**Comment by trubblegum** [comment]
Gspot is retained, not immediate.

Honestly, spritebatch is such a misleading and half-baked feature that I'm very reluctant to add native support for it. It may seem like it would be nice to have a wrapper for it that makes it more accessible, but in reality it's down to the guys who write love2d to make the naming and documentation usable.

At present, Gspot does it's best to optimize image usage, and I'm happy enough with that. It isn't really intended for writing an entire game.
